language: go
env:
  global:
  - GO111MODULE=on
go:
- '1.12'

# COVERALLS
#install:
#  - go get golang.org/x/tools/cmd/cover
#  - go get github.com/mattn/goveralls
#script:
#  - go test -v -covermode=count -coverprofile=coverage.out ./...
#  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN

# CODECOV
#before_install:
#  - go get -t -v ./...
#
#script:
#  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
#
#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# CODE CLIMATE
#env:
#  global:
#    - CC_TEST_REPORTER_ID=ABC123
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - go test -race -coverprofile c.out  -covermode atomic ./...
after_script:
  - sed -i'' -e 's/go-code-coverage-sample\///g' c.out
  - ./cc-test-reporter after-build --debug --exit-code $TRAVIS_TEST_RESULT
